# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='slack_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
