# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_githubuser_slack_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='login',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
