# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 17:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20160721_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='login',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
