# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
        ('repositories', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='user_management.GithubUser')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_issues', to='user_management.GithubUser')),
                ('labels', models.ManyToManyField(related_name='issues', to='labels.Label')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='repositories.Repository')),
            ],
            options={
                'ordering': ('repository', 'number'),
            },
        ),
    ]
