# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
        ('issues', '0002_auto_20160624_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('repository', '-number')},
        ),
        migrations.AddField(
            model_name='issue',
            name='estimate',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='pipelines.Pipeline'),
        ),
    ]
