# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20160624_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('repository', '-number')},
        ),
    ]
