# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issuecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
