# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20160630_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.Issue'),
        ),
    ]
