# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_auto_20160706_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='pipeline',
        ),
    ]
