# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('event', models.CharField(max_length=100)),
                ('handled', models.BooleanField(default=False)),
                ('method', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
