# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20160627_1732'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrequest',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.Issue'),
        ),
    ]
