# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_githubrequest_pull_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrequest',
            old_name='pull_request',
            new_name='pullrequest',
        ),
    ]
