# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160628_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrequest',
            name='action',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
