# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_githubrequest_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrequest',
            old_name='issue_comment',
            new_name='issuecomment',
        ),
    ]
