# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pull_requests', '0002_pullrequestcomment'),
        ('api', '0007_auto_20160628_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrequest',
            name='pullrequestcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pull_requests.PullRequestComment'),
        ),
    ]
