# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_githubrequest_pullrequestcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrequest',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='issues.Issue'),
        ),
    ]
