# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160712_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrequest',
            name='issuecomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='issues.IssueComment'),
        ),
        migrations.AlterField(
            model_name='githubrequest',
            name='pullrequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='pull_requests.PullRequest'),
        ),
        migrations.AlterField(
            model_name='githubrequest',
            name='pullrequestcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='pull_requests.PullRequestComment'),
        ),
    ]
