# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160712_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubrequest',
            options={'ordering': ('time',)},
        ),
    ]
