# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-23 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160805_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubrequest',
            options={'ordering': ('-time',)},
        ),
    ]
