# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20160628_1609'),
        ('pipelines', '0002_pipelinestates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_states', to='issues.Issue')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipelines.Pipeline')),
            ],
        ),
        migrations.RemoveField(
            model_name='pipelinestates',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='pipelinestates',
            name='pipeline',
        ),
        migrations.DeleteModel(
            name='PipelineStates',
        ),
    ]
