# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_auto_20160629_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinestate',
            options={'ordering': ('issue__repository', 'issue__number', 'started_at')},
        ),
    ]
