# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_auto_20160629_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinestate',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='pipelinestate',
            name='pipeline',
        ),
        migrations.DeleteModel(
            name='Pipeline',
        ),
        migrations.DeleteModel(
            name='PipelineState',
        ),
    ]
