# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0002_repository_pipelines'),
        ('user_management', '0002_githubuser_slack_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('body', models.TextField(default=b'')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=256)),
                ('assignees', models.ManyToManyField(related_name='assigned_pull_requests', to='user_management.GithubUser')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.Repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='user_management.GithubUser')),
            ],
        ),
    ]
