# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('repositories', models.ManyToManyField(related_name='labels', to='repositories.Repository')),
            ],
        ),
    ]
