# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_pipelines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='pipelines',
        ),
    ]
